speaker_index:
    path: /
    methods: [GET]
    controller: App\Speaker\Index\IndexAction::handle

speaker_create:
    path: /create
    methods: [GET, POST]
    controller: App\Speaker\Create\CreateAction::handle

speaker_show:
    path: /{id}
    methods: [GET]
    controller: App\Speaker\Show\ShowAction::handle
    requirements:
        id: '%routing.uuid%'

speaker_edit:
    path: /{id}/edit
    methods: [GET, POST, PUT]
    controller: App\Speaker\Edit\EditAction::handle
    requirements:
        id: '%routing.uuid%'

speaker_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Speaker\Delete\DeleteAction::handle
    requirements:
        id: '%routing.uuid%'

speaker_confirm_delete:
    path: /{id}/confirm_delete
    controller: App\Speaker\Delete\DeleteConfirmationAction:handle
    methods: [GET]
    requirements:
        id: '%routing.uuid%'

speaker_upload_from_openCFP:
    path: /uploadFromOpenCFP
    methods: [GET, POST]
    controller: App\Speaker\UploadFromOpenCfp\UploadFromOpenCfpAction::handle

speaker_send_interview:
    path: /{id}/send_interview
    methods: [GET, POST]
    controller: App\Speaker\Interview\SendInterviewAction::handle
    requirements:
        id: '%routing.uuid%'
