security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   app_logout

    access_control: ~

    encoders:
        App\Entity\User:
            algorithm: argon2i

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    