security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path:   app_logout

    access_control:
        - { path: /create, roles: ROLE_ADMIN }
        - { path: /%routing.uuid%/edit, roles: ROLE_ADMIN }
        - { path: /%routing.uuid%/delete, roles: ROLE_ADMIN }
        - { path: ^/sponsorship-level-benefit/edit, roles: ROLE_ADMIN }
        - { path: ^/organisations, roles: ROLE_USER }
        - { path: ^/sponsorship-level, roles: ROLE_USER }
        - { path: ^/sponsorship-level-benefit, roles: ROLE_USER }
        - { path: ^/speakers, roles: ROLE_USER }
        - { path: ^/special-benefit, roles: ROLE_USER }
        - { path: ^/sponsorship-benefit, roles: ROLE_USER }

    encoders:
        App\Entity\User:
            algorithm: argon2i

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
    