version: '3.7'

services:
    postgres:
        image: postgres:11
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
    php:
        build: ./docker/php-fpm
        volumes:
            - ./:/var/www/symfony:cached
            - ./var/logs/symfony:/var/www/symfony/var/logs:cached
            - ./php-fpm/php-limit.ini:/usr/local/etc/php/conf.d/php-limit.ini
        depends_on:
            - postgres
    node:
        image: node:11
        volumes:
            - ./:/var/www/symfony
        working_dir: /var/www/symfony
        environment:
            NODE_ENV: development
        command: sh -c "yarn install && yarn encore dev --watch"
    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        depends_on:
            - php
        volumes:
            - ./:/var/www/symfony:cached
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/logs/nginx/:/var/log/nginx:cached
    composer:
        image: composer:latest
        volumes:
            - .:/app
    storage:
        image: minio/minio:latest
        ports:
            - '9001:9000'
        environment:
            - MINIO_ACCESS_KEY=${S3_KEY}
            - MINIO_SECRET_KEY=${S3_SECRET}
        volumes:
            - ./var/s3:/data
        command: 'server /data'
    hub:
        image: elgalu/selenium
        volumes:
          - /dev/shm:/dev/shm
        privileged: true
        environment:
          - SELENIUM_HUB_HOST=hub
          - SELENIUM_HUB_PORT=4445
          - GRID=true
          - CHROME=false
          - FIREFOX=false
        depends_on:
          - php
    chrome:
        image: elgalu/selenium
        depends_on:
          - hub
        volumes:
          - /dev/shm:/dev/shm
        privileged: true
        environment:
          - NOVNC=true
          - SELENIUM_HUB_HOST=hub
          - SELENIUM_HUB_PORT=4445
          - SELENIUM_NODE_HOST={{CONTAINER_IP}}
          - SCREEN_WIDTH=1300
          - SCREEN_HEIGHT=999
          - VIDEO=false
          - GRID=false
          - CHROME=true
          - FIREFOX=false

        ports:
          - 6080:26080
