version: '3.7'

services:
    postgres:
        image: postgres:11
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
    php:
        build: php-fpm
        volumes:
            - ./:/var/www/symfony:cached
            - ./var/logs/symfony:/var/www/symfony/var/logs:cached
        depends_on:
            - postgres
    node:
        image: node:alpine
        volumes:
            - ./:/var/www/symfony
        working_dir: /var/www/symfony
        environment:
            NODE_ENV: development
        command: sh -c "yarn install && yarn encore dev"
        restart: "no"
    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        depends_on:
            - php
        volumes:
            - ./:/var/www/symfony:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/logs/nginx/:/var/log/nginx:cached
    composer:
        image: composer:latest
        volumes:
            - .:/app
        command: 'install'
    storage:
        image: minio/minio:latest
        ports:
          - '9001:9000'
        volumes:
          - ./var/s3:/data
        command: 'server /data'
