version: '3.7'

services:
    postgres:
        image: postgres
    php:
        build: php-fpm
        volumes:
            - ./:/var/www/symfony:cached
            - ./var/logs/symfony:/var/www/symfony/var/logs:cached
        depends_on:
            - postgres
    nginx:
        image: nginx:latest
        ports:
            - '8080:80'
        depends_on:
            - php
        volumes:
            - ./:/var/www/symfony:cached
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/logs/nginx/:/var/log/nginx:cached
    composer:
        image: composer:latest
        volumes:
            - .:/app
        command: 'install'
    storage:
        image: minio/minio:latest
        ports:
          - '9001:9000'
        volumes:
          - ./var/s3:/data
        command: 'server /data'
