organisation_list:
    controller: App\Controller\Organisation\Index::handle
    path: /

organisation_create:
    controller: App\Controller\Organisation\Create::handle
    path: /create

organisation_show:
    controller: App\Controller\Organisation\Show:handle
    path: /{id}
    requirements:
        id: '\d+'

organisation_edit:
    controller: App\Controller\Organisation\Edit:handle
    path: /{id}/edit
    requirements:
        id: '\d+'

organisation_delete:
    controller: App\Controller\Organisation\Delete:handle
    path: /{id}/delete
    methods: [DELETE]
    requirements:
        id: '\d+'