organisation_list:
    controller: App\Controller\Organisation\Index::handle
    path: /

organisation_create:
    controller: App\Controller\Organisation\Create::handle
    path: /create

organisation_show:
    controller: App\Controller\Organisation\Show:handle
    path: /{id}
    requirements:
        id: '\d+'
