schedule_index:
  path: /
  controller: App\Controller\Schedule\Index::handle
  methods: [GET]

schedule_create:
  path: /create
  controller: App\Controller\Schedule\Create::handle
  methods: [GET, POST]

schedule_space_insert:
  path: /space/create
  controller: App\Controller\Space\Create::handle
  methods: [POST]