schedule_index:
    path: /
    controller: App\Controller\Schedule\Index::handle
    methods: [GET]
    options:
        expose: true

schedule_create:
    path: /create
    controller: App\Controller\Schedule\Create::handle
    methods: [GET, POST]

schedule_schedule_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Controller\Schedule\Delete::handle
    requirements:
        id: '%routing.uuid%'

schedule_space_insert:
    path: /space/create
    controller: App\Controller\Space\Create::handle
    methods: [POST]

schedule_space_delete:
    path: /space/{id}/delete
    methods: [DELETE]
    controller: App\Controller\Space\Delete::handle
    requirements:
        id: '%routing.uuid%'

schedule_slot_insert:
    path: /slot/create
    controller: App\Controller\Slot\Create::handle
    methods: [POST]

schedule_slot_edit:
    path: /slot/{id}/edit
    methods: [GET, PUT]
    controller: App\Controller\Slot\Edit::handle
    requirements:
        id: '%routing.uuid%'

schedule_slot_delete:
    path: /slot/{id}/delete
    methods: [DELETE]
    controller: App\Controller\Slot\Delete::handle
    requirements:
        id: '%routing.uuid%'

schedule_slot_type_index:
  path: /slot-type/
  controller: App\Controller\SlotType\Index::handle
  methods: [GET]

schedule_slot_type_create:
  path: /slot-type/create
  controller: App\Controller\SlotType\Create::handle
  methods: [GET, POST]

schedule_slot_type_edit:
  path: /slot-type/{id}/edit
  methods: [GET, PUT]
  controller: App\Controller\SlotType\Edit::handle
  requirements:
    id: '%routing.uuid%'

schedule_slot_type_delete:
  path: /slot-type/{id}/delete
  methods: [DELETE]
  controller: App\Controller\SlotType\Delete::handle
  requirements:
    id: '%routing.uuid%'

schedule_duplicate_item:
  path: /{id}/confirm_duplicate
  methods: [GET, POST]
  controller: App\Controller\Schedule\Duplicate::handle
  requirements:
    id: '%routing.uuid%'

schedule_confirm_delete:
    path: /{id}/confirm_delete
    controller: App\Controller\Schedule\DeleteConfirmation:handle
    methods: [GET]
    requirements:
        id: '%routing.uuid%'

schedule_space_type_index:
    path: /space-types/
    controller: App\Controller\SpaceType\Index::handle
    methods: [GET]

schedule_space_type_create:
    path: /space-types/create
    controller: App\Controller\SpaceType\Create::handle
    methods: [GET, POST]

schedule_space_type_edit:
    path: /space-types/{id}/edit
    controller: App\Controller\SpaceType\Edit::handle
    methods: [GET, POST]
    requirements:
        id: '%routing.uuid%'

schedule_space_type_delete:
    path: /space-types/{id}/delete
    controller: App\Controller\SpaceType\Delete::handle
    methods: [DELETE]
    requirements:
        id: '%routing.uuid%'
