schedule_index:
  path: /
  controller: App\Controller\Schedule\Index::handle
  methods: [GET]

schedule_create:
  path: /create
  controller: App\Controller\Schedule\Create::handle
  methods: [GET, POST]

schedule_schedule_delete:
  path: /{id}/delete
  methods: [DELETE]
  controller: App\Controller\Schedule\Delete::handle
  requirements:
    id: '%routing.uuid%'

schedule_space_insert:
  path: /space/create
  controller: App\Controller\Space\Create::handle
  methods: [POST]

schedule_space_delete:
  path: /space/{id}/delete
  methods: [DELETE]
  controller: App\Controller\Space\Delete::handle
  requirements:
    id: '%routing.uuid%'

schedule_slot_insert:
  path: /slot/create
  controller: App\Controller\Slot\Create::handle
  methods: [POST]

schedule_slot_edit:
  path: /slot/{id}/edit
  methods: [GET, POST, PUT]
  controller: App\Controller\Slot\Edit::handle
  requirements:
    id: '%routing.uuid%'

schedule_slot_delete:
  path: /slot/{id}/delete
  methods: [DELETE]
  controller: App\Controller\Slot\Delete::handle
  requirements:
    id: '%routing.uuid%'
