speaker_index:
    path: /
    methods: [GET]
    controller: App\Controller\Speaker\Index::handle

speaker_create:
    path: /create
    methods: [GET, POST]
    controller: App\Controller\Speaker\Create::handle

speaker_show:
    path: /{id}
    methods: [GET]
    controller: App\Controller\Speaker\Show::handle
    requirements:
        id: '%routing.uuid%'

speaker_edit:
    path: /{id}/edit
    methods: [GET, POST, PUT]
    controller: App\Controller\Speaker\Edit::handle
    requirements:
        id: '%routing.uuid%'

speaker_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Controller\Speaker\Delete::handle
    requirements:
        id: '%routing.uuid%'

speaker_confirm_delete:
    path: /{id}/confirm_delete
    controller: App\Controller\Speaker\DeleteConfirmation:handle
    methods: [GET]
    requirements:
        id: '%routing.uuid%'

speaker_upload_from_openCFP:
    path: /uploadFromOpenCFP
    methods: [GET, POST]
    controller: App\Controller\Speaker\UploadFromOpenCfp::handle

speaker_send_interview:
    path: /{id}/send_interview
    methods: [GET, POST]
    controller: App\Controller\Speaker\SendInterview::handle
    requirements:
        id: '%routing.uuid%'
