special_sponsorship_index:
    path: /
    methods: [GET]
    controller: App\Controller\SpecialSponsorship\Index::handle

special_sponsorship_create:
    path: /create
    methods: [GET, POST]
    controller: App\Controller\SpecialSponsorship\Create::handle

special_sponsorship_edit:
    path: /{id}/edit
    methods: [GET, PUT]
    controller: App\Controller\SpecialSponsorship\Edit::handle
    requirements:
        id: '%routing.uuid%'

special_sponsorship_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Controller\SpecialSponsorship\Delete::handle
    requirements:
        id: '%routing.uuid%'

special_sponsorship_show:
    path: /{id}
    controller: App\Controller\SpecialSponsorship\Show:handle
    methods: [GET]
    requirements:
        id: '%routing.uuid%'
