sponsorship_level_index:
    path: /
    methods: [GET]
    controller: App\Controller\SponsorshipLevel\Index::handle

sponsorship_level_create:
    path: /create
    methods: [GET, POST]
    controller: App\Controller\SponsorshipLevel\Create::handle

sponsorship_level_edit:
    path: /{id}/edit
    methods: [GET, PUT]
    controller: App\Controller\SponsorshipLevel\Edit::handle
    requirements:
        id: '%routing.uuid%'

sponsorship_level_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Controller\SponsorshipLevel\Delete::handle
    requirements:
        id: '%routing.uuid%'
