talk_index:
    path: /
    methods: [GET]
    controller: App\Controller\Talk\Index::handle

talk_create:
    path: /create
    methods: [GET, POST]
    controller: App\Controller\Talk\Create::handle

talk_show:
    path: /{id}
    methods: [GET]
    controller: App\Controller\Talk\Show::handle
    requirements:
        id: '%routing.uuid%'

talk_edit:
    path: /{id}/edit
    methods: [GET, POST, PUT]
    controller: App\Controller\Talk\Edit::handle
    requirements:
        id: '%routing.uuid%'

talk_delete:
    path: /{id}/delete
    methods: [DELETE]
    controller: App\Controller\Talk\Delete::handle
    requirements:
        id: '%routing.uuid%'
