sponsorship_level:
  resource: routes/sponsorshipLevel.yaml
  prefix: sponsorship-level

sponsorship_benefit:
  resource: routes/sponsorshipBenefit.yaml
  prefix: sponsorship-benefit

sponsorship_level_benefit:
  resource: routes/sponsorshipLevelBenefit.yaml
  prefix: sponsorship-level-benefit

special_benefit:
  resource: routes/specialBenefit.yaml
  prefix: special-benefit
