services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $currency: '%currency%'


  _instanceof:
    App\Action:
      tags: [controller.service_arguments]

  App\Sponsorship\:
    resource: '../../'
