sponsorship_level_benefit_view:
    path: /
    methods: [GET]
    controller: App\Sponsorship\SponsorshipLevelBenefit\View\ViewAction::handle

sponsorship_level_benefit_edit:
    path: /edit
    methods: [GET]
    controller: App\Sponsorship\SponsorshipLevelBenefit\Edit\EditAction::handle

sponsorship_level_benefit_edit_level_position:
    path: /edit-sponsorship-level-position
    methods: [PUT]
    controller: App\Sponsorship\SponsorshipLevelBenefit\Edit\EditLevelPositionAction::handle
    options:
        expose: true

sponsorship_level_benefit_edit_benefit_position:
    path: /edit-sponsorship-benefit-position
    methods: [PUT]
    controller: App\Sponsorship\SponsorshipLevelBenefit\Edit\EditBenefitPositionAction::handle
    options:
        expose: true

sponsorship_level_benefit_edit_datas:
    path: /edit-datas
    methods: [PUT]
    controller: App\Sponsorship\SponsorshipLevelBenefit\Edit\EditDataAction::handle
    options:
        expose: true
