services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    App\Action:
      tags: [controller.service_arguments]

  App\Schedule\:
    resource: '../../'
